---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frequency
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: frequency
      name: frequency
      namespace: default
    spec:
      containers:
      - env:
        - name: MIX_ENV
          value: prod
        image: 585031190124.dkr.ecr.us-east-1.amazonaws.com/frequency:production
        imagePullPolicy: Always
        name: frequency
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: frequency
  name: frequency
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: frequency
  sessionAffinity: None
  type: LoadBalancer
